### ISSUE TITLE
Conflicting libraries on classpath

### ISSUE THREAD

**Issue by baszero** [wyona/yanel#83]
When I build Yanel, I see these two JARs in the `WEB-INF/lib` folder:
```
commons-io-1.2.jar
commons-io-2.4.jar
```

The following should be done:
- What code is requiring 2.4? (because in the Yanel dependencies.xml only 1.2 is referenced)
- Is version 2.x compatible with 1.x ? If so, Yanel should upgrade to v2.4 in order to remove this library conflict.

**Comment by michaelwechner** [comment]
I guess we can upgrade to 2.4 inside

src/build/dependencies.xml 

but also see the property
duplicated.libs
inside
src/build/build.properties

**Comment by michaelwechner** [comment]
I have fixed this now

git ci -m "commons-io upgraded to 2.4 and made sure that older version 1.2 is not getting copied" src/build/build.properties src/build/dependencies.xml 

Also see

https://www.yulup.com/en/projects/yanel/changes.html?branch=master#b40c7293-d440-46fd-8093-66441da5bd71

**Comment by baszero** [comment]
Many thanks!
